### ISSUE TITLE
bug: uptsream nodes in apisix does not update when we logout all instances in nacos

### ISSUE THREAD

**Issue by soulbird** [api7/apisix-seed#27]
When we logout all instances in nacos via api like:
```bash
curl -X DELETE 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=APISIX-NACOS&ip=127.0.0.1&port=10000'
```
We expect the node information in etcd to be updated as well, but it not.

**Comment by soulbird** [comment]
It seems that `[nacos-sdk-go](https://github.com/nacos-group/nacos-sdk-go)` will not notify apisix-seed, although we use the subscription interface https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/naming_client/naming_client.go#L313

Maybe we can pull node information from nacos periodically like Apache APISIX: https://github.com/apache/apisix/blob/master/apisix/discovery/nacos/init.lua#L383

**Comment by spacewander** [comment]
Would you submit an issue to nacos-sdk-go and ask for help?

**Comment by soulbird** [comment]
> Would you submit an issue to nacos-sdk-go and ask for help?

ok， I'll try it first
