### ISSUE TITLE
Clearer flowchart

### ISSUE THREAD

**Issue by membphis** [api7/apisix-seed#48]
The first one:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6814606/167234745-70d69081-8310-4404-8049-d415f0115b0e.png">

The second one:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6814606/167234769-f9d2b34b-d170-4969-957a-fddef31013d2.png">

**Comment by soulbird** [comment]
Updated.
