### ISSUE TITLE
apisix-seed部署起来了，但是没有日志输出

### ISSUE THREAD

**Issue by danchunTT** [api7/apisix-seed#50]
apisix-seed在自己的容器里部署起来了，但是没有日志输出，请问是什么原因？

**Comment by danchunTT** [comment]
我讲下背景：
我从git上把代码拉下来，改动配置文件，配置上了zk 相关的信息，打成镜像，发布到我们自己的公司的镜像库了，发布部署。服务显示run起来了，但是没有日志输出。

配置文件的内容：

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://xx.xx.xx.xx:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
  prefix: /apisix                 # apisix configurations prefix
  timeout: 30                     # 30 seconds
  #user: root                     # root username for etcd
  #password: 5tHkHhYkjr6cQY       # root password for etcd
  tls:
    #cert: /path/to/cert          # path of certificate used by the etcd client
    #key: /path/to/key            # path of key used by the etcd client

    verify: true                  # whether to verify the etcd endpoint certificate when setup a TLS connection to etcd,
    # the default value is true, e.g. the certificate will be verified strictly.

discovery:                       # service discovery center              # default 5000ms
  zookeeper:
    hosts:
      - "xx.zz.zz.zz:2181"
    prefix: /com/apisix
    weight: 100                  # default weight for node
    timeout: 10                  # default 10s

**Comment by soulbird** [comment]
If you build the image with a Dockerfile, there will be no log output when APISIX-Seed runs, which is bad. I will fix it.

**Comment by soulbird** [comment]
You can use error redirection when starting apisix-seed, like this:
```bash
/usr/local/apisix-seed/apisix-seed >/usr/local/apisix-seed/log/error.log 2>&1
```

**Comment by danchunTT** [comment]
1. apisix、apisix-seed、etcd、zk服务都已启动成功；
2. apisix-seed配置内容：
etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://127.0.0.1:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
  prefix: /apisix                 # apisix configurations prefix
  timeout: 30                     # 30 seconds
  #user: root                     # root username for etcd
  #password: 5tHkHhYkjr6cQY       # root password for etcd
  tls:
    #cert: /path/to/cert          # path of certificate used by the etcd client
    #key: /path/to/key            # path of key used by the etcd client

    verify: true                  # whether to verify the etcd endpoint certificate when setup a TLS connection to etcd,
    # the default value is true, e.g. the certificate will be verified strictly.

discovery:                       # service discovery center
  zookeeper:
    hosts:
      - "127.0.0.1:2181"
    prefix: /com
    weight: 100                  # default weight for node
    timeout: 10                  # default 10s

3. 通过Admin的API创建理由
3.1 通过postman进行请求
POST  apisix/admin/routes
参数为：
{
    "uri": "/servicer/custom/plugin",
    "upstream": {
        "discovery_type": "zookeeper",
        "service_name": "test1",
        "type": "roundrobin"
    }
}
4. 查看etcd的数据：
/apisix/routes/00000000000000041640
{"upstream":{"service_name":"test1","type":"roundrobin","hash_on":"vars","discovery_type":"zookeeper","scheme":"http","pass_host":"pass"},"priority":0,"create_time":1653030841,"id":"00000000000000041640","update_time":1653030841,"uri":"\/servicer\/custom\/plugin","status":1}
5. zk的内容如下：
{
  "host": "10.38.207.24",
  "port": "8012"
}
6. apisix-seed没有任何日志

**Comment by danchunTT** [comment]
apisix -seed seems not to work,please can look at?

**Comment by danchunTT** [comment]
我说下，将seed部署到我们公司的容器步骤：
1.下载源码，然后docker build ，生成镜像a
2.吧镜像a推到我们公司仓库；
3，重写dokerfile ,内容如下：
FROM aaaaaaaa/seed-10005:latest
WORKDIR /usr/local/apisix-seed
COPY conf/conf.yaml conf/conf.yaml

ENV PATH=$PATH:/usr/local/apisix-seed
ENV APISIX_SEED_WORKDIR /usr/local/apisix-seed
CMD [ "/usr/local/apisix-seed/apisix-seed >/usr/local/apisix-seed/log/error.log 2>&1" ]

我不知道这个步骤思路有没有问题？
